ARG IMAGE
FROM $IMAGE
MAINTAINER Romain Beauxis <toots@rastageeks.org>

USER root

RUN rm -rf /home/opam/opam-cross-osx/packages

ADD packages/ /home/opam/opam-cross-osx/packages

ADD repo /home/opam/opam-cross-osx/repo

RUN chown -R opam /home/opam/opam-cross-osx

USER opam

RUN opam update
