ARG IMAGE
FROM $IMAGE
MAINTAINER Romain Beauxis <toots@rastageeks.org>

ARG COMPILER
ARG SYSTEM

RUN sed -i /etc/apt/sources.list -e 's#jessie#testing#g' && (apt-get update || true) && \
      apt-get install -y --force-yes gawk aspcud binutils automake lzip && \
      apt-get -y --force-yes autoremove && apt-get -y --force-yes clean

RUN wget https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh -O /tmp/install.sh && echo /usr/local/bin | sh /tmp/install.sh

RUN useradd -g staff --create-home opam

USER opam

ENV CC="" CPP="" CXX="" LD="" AS="" AR=""

RUN opam init --auto --compiler=$COMPILER --disable-sandboxing

USER root

ADD packages/ /home/opam/opam-cross-osx/packages

ADD repo /home/opam/opam-cross-osx/repo

RUN chown -R opam /home/opam/opam-cross-osx

USER opam

WORKDIR /home/opam/opam-cross-osx

RUN opam repository add osx /home/opam/opam-cross-osx

RUN if [ "$SYSTEM" = "x64" ]; then \
      export TOOLPREF64=/usr/src/mxe/usr/bin/x86_64-w64-mingw32.static- && \
      eval $(opam env) && \
      opam install -y -v ocaml-osx ocaml-osx64; \
    fi

RUN if [ "$SYSTEM" = "x86" ]; then \
      export TOOLPREF32=/usr/src/mxe/usr/bin/i686-w64-mingw32.static- && \
      eval $(opam env) && \
      opam install -y ocaml-osx ocaml-osx32; \
    fi
